### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode character

### ISSUE THREAD

**Issue by turing4ever** [dancingcactus/python-omniture#65]
Hi all, 

I run into this issue when I am trying out this package:
UnicodeEncodeError: 'ascii' codec can't encode character u'\xa0' in position 53: ordinal not in range(128)

Has anyone seen the same issue? 
I resolved this issue by modifying one line of code in site-packages/omniture/elements.py: 
at line 15, changing self.title = str(title) into #self.title = title

Any idea why this is happening and is there any better resolution?

Thanks!

**Comment by dancingcactus** [comment]
This usually happens because there is either a multibyte character or more commonly a truncated multi-byte character in the data you are trying to pull. JSON only supports ASCII and as the conversion doesn't go so well (especially when the character is truncated). Many times you can add 

.set("elementDataEncoding","utf8") that will sometimes fix it. 

Details can be found [here](https://marketing.adobe.com/developer/documentation/analytics-reporting-1-4/r-reportdescription-1)

**Comment by bhdavis1978** [comment]
Hi DancingCactus,
Can you explain to me where I would execute this command w.r.t. the report generation? Specifically, I"m executing the command

`report2 = suite.report.element('page').metric('pageviews').run()`

Which generates the aforementioned 

`UnicodeEncodeError: 'ascii' codec can't encode character u'\u2019' in position 21: ordinal not in range(128)`

However if I excecute
`report = suite.report.element('evar85').run()`

and then view report, I get a reasonable output. 

Specifically it looks like this

evar85      pageviews
12341431           351
84871934           324
38481593           73
etc
etc
So I'm a little confused.  

 Can you help me out?
